DROP TABLE ODONTOLOGOS IF EXISTS;

CREATE TABLE ODONTOLOGOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
MATRICULA VARCHAR(50) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL
);

INSERT INTO ODONTOLOGOS VALUES (DEFAULT, 'A503', 'MIGUEL','BORJA'),
(DEFAULT, 'A302', 'MARCELO','GALLARDO'), (DEFAULT, 'A659', 'ENZO','PEREZ');